id: extract_load_gcp
namespace: scraping

inputs:
  - name: parent_datafile
    type: FILE

tasks:

  - id: log
    type: io.kestra.core.tasks.log.Log
    message: "{{ inputs.parent_datafile }}"

  - id: extract
    type: io.kestra.plugin.gcp.gcs.Upload
    from: '{{ inputs.parent_datafile }}'
    to: "gs://bpimpaud-demo/scraping/{{ taskrun.startDate | date('YYYYMMdd') }}/cars_data_{{ taskrun.startDate | date('YYYYMMdd') }}.json"

  - id: load
    type: io.kestra.plugin.gcp.bigquery.LoadFromGcs
    from:
      - '{{ outputs.extract.uri}}'
    destinationTable: "kestra-dev.scraping_demo.cars_data_{{ taskrun.startDate | date('YYYYMMdd') }}"
    autodetect: true
    format: JSON

triggers:
  - id: listen-flow
    type: io.kestra.core.models.triggers.types.Flow
    inputs:
      parent_datafile: '{{ outputs.concat.uri }}'
    conditions:
      - type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
        namespace: scraping
        flowId: scrape-ebay
      - type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
        in:
          - SUCCESS
