id: git-sync
namespace: integration
tasks:

  - id: git-sync
    type: io.kestra.plugin.git.Sync
    url: https://github.com/Ben8t/kestra_prod
    branch: test-git-ops
    username: Ben8t
    gitDirectory: ./_flows/main_namespace
    namespaceFilesDirectory: ns_script
    password: "{{ secret('GITHUB') }}"
    
triggers:
  - id: every_minute
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "*/1 * * * *"