id: dbt
namespace: demo

tasks:

  - id: working_dir
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:

      - id: clone
        type: io.kestra.plugin.git.Clone
        url: https://github.com/Ben8t/kestra_dbt
        branch: main

      - id: local_file
        type: io.kestra.core.tasks.storages.LocalFiles
        inputs:
          conf/profiles.yml: |
            kestra_dbt:
              outputs:
                dev:
                  type: bigquery
                  dataset: demo
                  fixed_retries: 1
                  keyfile: gcp_service_account.json
                  location: EU
                  method: service-account
                  priority: interactive
                  project: kestra-dev
                  threads: 8
                  timeout_seconds: 300
              target: dev
          gcp_service_account.json: |
            {{ secret('gcp_creds') }}

      - id: dbt_run
        type: io.kestra.plugin.scripts.shell.Commands
        docker:
          image: ghcr.io/kestra-io/dbt-bigquery:latest
        commands:
          - dbt run --profiles-dir=./conf
triggers:
  - id: multiple-listen-flow
    type: io.kestra.core.models.triggers.types.Flow
    conditions:
      - type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
        in:
          - SUCCESS
      - id: multiple
        type: io.kestra.core.models.conditions.types.MultipleCondition
        window: P1D
        windowAdvance: P0D
        conditions:
          flow_a:
            type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
            namespace: demo
            flowId: airbyte
          flow_b:
            type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
            namespace: demo
            flowId: api_extract