id: gcs_trigger_cloud_run
namespace: demo.kestra

tasks:

  - id: slack
    disabled: true
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: "https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX"
    payload: |
      {
        "channel": "#my-chan",
        "text": "Flow {{ flow.namespace }}.{{ flow.id }} started with execution {{ execution.id }}"
      }

  - id: log
    type: io.kestra.core.tasks.log.Log
    message: "{{ trigger.blobs | jq('.[].uri') }}"


  - id: cloud_run
    disabled: true
    type: io.kestra.plugin.fs.http.Request
    uri: '{{ vars.cloud_run_endpoint }}'
    headers:
      Authorization: 'Bearer {{ envs.cloud_run_token }}'
    formData:
      data: "{{ trigger.blobs | jq('.[].selfLink') }}"


triggers:

  - id: gcs
    type: io.kestra.plugin.gcp.gcs.Trigger
    interval: "PT1M"
    from: gs://bpimpaud-demo/listen/
    moveDirectory: gs://bpimpaud-demo/to_process/
    action: MOVE
    regExp: '.*csv'