id: ingest_data_from_ftp
namespace: demo.believe
description: |
  Here is the docker command to emulate a FTP server locally
  ```
  docker container run -d \
    -p 21:21 \
    -p 21000-21010:21000-21010 \
    -e USERS="admin|kestra" --network kestra-net \
    --name local_ftp \
    delfer/alpine-ftp-server
  ```

  if you want to log in with a shell
  ```
  docker exec -it local_ftp /bin/sh
  ```

labels:
  tag: TRIGGER
  
variables:
  bucket: "kestra-demo"
  key: "spotify/top_chart.csv"

tasks:

  - id: upload_s3
    type: io.kestra.plugin.aws.s3.Upload
    accessKeyId: '{{ secret("AWS_KEY")}}'
    secretKeyId: '{{ secret("AWS_SECRET") }}'
    region: 'eu-north-1'
    from: '{{ trigger.files[0].path }}'
    bucket: '{{ vars.bucket }}'
    key: '{{ vars.key }}'

  - id: aws_lambda
    type: io.kestra.plugin.aws.lambda.Invoke
    accessKeyId: '{{ secret("AWS_KEY")}}'
    secretKeyId: '{{ secret("AWS_SECRET") }}'
    region: 'eu-north-1'
    functionArn: arn:aws:lambda:eu-north-1:070823507174:function:process_data
    functionPayload:
      bucket: '{{ vars.bucket }}'
      key: '{{ vars.key }}'


triggers:
  - id: listen_ftp
    type: io.kestra.plugin.fs.ftp.Trigger
    host: host.docker.internal
    port: "21"
    username: "{{ secret('FTP_USER') }}"
    password: "{{ secret('FTP_PASSWORD') }}"
    from: "./input/"
    interval: PT1S
    action: MOVE
    moveDirectory: "./archive/"