id: metric_demo
namespace: demo.kestra

tasks:
  - id: process
    type: io.kestra.core.tasks.scripts.Bash
    commands:
      - RANDOM=$$$(date +%s)
      - random_number=$(( RANDOM % 4 ))
      - echo "Sleep for $random_number"
      - sleep "$(( RANDOM % 4 ))"
      - echo "::{\"metrics\":[{\"name\":\"time\",\"type\":\"timer\",\"value\":$random_number}]}::"

triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: 0 */2 * * *