id: schedule_eveday_at_six
namespace: blueprint
description: |
  **Schedule a Flow everyday at 6:30AM**

labels:
  tag: SCHEDULE & TRIGGER

tasks:
  - id: log
    type: io.kestra.core.tasks.log.Log
    message: It's {{ schedule.date ?? taskrun.startDate | date("HH:mm") }} # if the flow is ran manually it will print the taskrun start date. We also filter to only display hours and minutes

triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "30 6 * * *"
