kestra_dbt:
  outputs:
    dev:
      type: bigquery
      dataset: demo_converteo
      fixed_retries: 1
      keyfile: ../gcp_service_account/kestra-dev.json
      location: EU
      method: service-account
      priority: interactive
      project: kestra-dev
      threads: 8
      timeout_seconds: 300
  target: dev