id: parse_fbref
namespace: dev.malloy

inputs:
  - name: date
    type: DATE

tasks:
  - id: wd
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:

      - id: git_clone
        type: io.kestra.plugin.git.Clone
        url: https://github.com/Ben8t/fbref_scraper

      - id: python
        type: io.kestra.plugin.scripts.python.Commands
        docker:
          image: ghcr.io/kestra-io/pydata
          volumes:
            - /Users/benoit/dev/kestra/kestra_prod/data:/tmp/data
        warningOnStdErr: false
        beforeCommands:
          - pip install -r requirements.txt
        commands:
          - python main.py --date {{ inputs.date }} --page fixtures/ --fixture_url=https://fbref.com/en/comps/9/schedule/Premier-League-Scores-and-Fixtures --data_dir=/tmp/data
          - python main.py --date {{ inputs.date }} --page matchs/ --data_dir=/tmp/data

triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "@daily"
